import type { Product } from './types';

// Shelf positions:
// Aisle 1 (Left): x = -11, y = 3.25, z = -10 to 10
// Aisle 2 (Right): x = 11, y = 3.25, z = -10 to 10
// Aisle 3 (Back): z = -19, y = 3.25, x = -6 to 6

export const products: Product[] = [
  // Aisle 1: Groceries & Pharmacy
  {
    id: 1,
    name: 'Great Value Milk',
    price: 3.5,
    description: 'Fresh and nutritious whole milk. A household essential.',
    image: 'https://placehold.co/400x400.png',
    category: 'Groceries',
    position: [-11, 3.75, -10],
    size: [0.5, 1.5, 0.5],
  },
  {
    id: 3,
    name: 'Marketside Pizza',
    price: 5.0,
    description: 'Delicious pepperoni pizza, ready to bake.',
    image: 'https://placehold.co/400x400.png',
    category: 'Groceries',
    position: [-11, 3.35, -7],
    size: [1.2, 0.2, 1.2],
  },
  {
    id: 12,
    name: 'Great Value Eggs',
    price: 2.50,
    description: 'One dozen Grade A large eggs.',
    image: 'https://placehold.co/400x400.png',
    category: 'Groceries',
    position: [-11, 3.6, -4],
    size: [1, 0.7, 0.5],
  },
  {
    id: 2,
    name: 'Equate Ibuprofen',
    price: 8.98,
    description: 'Pain reliever and fever reducer. 200mg tablets.',
    image: 'https://placehold.co/400x400.png',
    category: 'Pharmacy',
    position: [-11, 3.5, 8],
    size: [0.4, 0.8, 0.3],
  },
  {
    id: 13,
    name: 'Equate Allergy Relief',
    price: 12.48,
    description: '24-hour non-drowsy allergy relief tablets.',
    image: 'https://placehold.co/400x400.png',
    category: 'Pharmacy',
    position: [-11, 3.5, 10],
    size: [0.4, 0.8, 0.3],
  },

  // Aisle 2: Apparel, Outdoors, Home Goods
  {
    id: 5,
    name: 'Hanes T-Shirt',
    price: 6.0,
    description: 'Comfortable and durable 100% cotton crewneck t-shirt.',
    image: 'https://placehold.co/400x400.png',
    category: 'Apparel',
    position: [11, 3.3, -8],
    size: [0.8, 0.1, 1],
  },
   {
    id: 6,
    name: 'Ozark Trail Tent',
    price: 49.99,
    description: '4-person dome tent, perfect for camping trips.',
    image: 'https://placehold.co/400x400.png',
    category: 'Outdoors',
    position: [11, 4, 4],
    size: [2, 2, 2],
  },
  {
    id: 9,
    name: 'Spalding Basketball',
    price: 15.88,
    description: 'Official size and weight street basketball.',
    image: 'https://placehold.co/400x400.png',
    category: 'Sporting Goods',
    position: [11, 3.75, 8],
    size: [1, 1, 1],
  },
  {
    id: 7,
    name: 'Mainstays Bath Towel',
    price: 4.97,
    description: 'Soft and absorbent 100% cotton bath towel.',
    image: 'https://placehold.co/400x400.png',
    category: 'Home Goods',
    position: [11, 3.3, 0],
    size: [1.5, 0.2, 1],
  },
  {
    id: 10,
    name: 'T-fal Cookware Set',
    price: 69.99,
    description: '18-piece nonstick cookware set, perfect for any kitchen.',
    image: 'https://placehold.co/400x400.png',
    category: 'Home Goods',
    position: [11, 4, -2],
    size: [2, 1.5, 2],
  },

  // Aisle 3: Electronics & Toys
  {
    id: 4,
    name: 'onn. 50" TV',
    price: 198.0,
    description: '50" Class 4K UHD (2160P) LED Roku Smart TV.',
    image: 'https://placehold.co/400x400.png',
    category: 'Electronics',
    position: [-5, 4.25, -19],
    size: [0.2, 2.5, 4.5],
  },
    {
    id: 14,
    name: 'onn. Bluetooth Speaker',
    price: 20.00,
    description: 'Portable bluetooth speaker with 8 hours of playtime.',
    image: 'https://placehold.co/400x400.png',
    category: 'Electronics',
    position: [-1, 3.5, -19],
    size: [0.8, 0.5, 0.4],
  },
  {
    id: 8,
    name: 'LEGO Classic Bricks',
    price: 20.00,
    description: 'A box of 484 classic LEGO bricks for creative building.',
    image: 'https://placehold.co/400x400.png',
    category: 'Toys',
    position: [3, 3.7, -19],
    size: [1.2, 0.8, 0.5],
  },
  {
    id: 11,
    name: 'Barbie Dreamhouse',
    price: 179.00,
    description: 'The ultimate dollhouse with 3 stories, 8 rooms, and a working elevator.',
    image: 'https://placehold.co/400x400.png',
    category: 'Toys',
    position: [6, 4.5, -19],
    size: [2.5, 3, 1],
  },
];

export const trendingProducts: string[] = [
  'onn. 50" TV',
  'Marketside Pizza',
  'Great Value Milk',
  'LEGO Classic Bricks',
  'Spalding Basketball',
];
